name: borderless
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_slidable: ^2.0.0
  http: ^0.13.3
  path_provider: ^2.0.11
  provider: ^5.0.0
  image_picker: ^0.8.4+4
  geolocator: ^9.0.2
  geocoding: ^2.0.1
  flutter_osm_plugin: ^0.39.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  image_path: assets/logo.png
  adaptive_icon_background: assets/back.png
  adaptive_icon_foreground: assets/logo-rec.png
flutter:
  uses-material-design: true